sonar.projectKey=fatenmars_p7-microcrm
sonar.organization=fatenmars

# Code de production
sonar.sources=back/src/main,front/src
# Code de test
sonar.tests=back/src/test,front/src
sonar.test.inclusions=**/*.spec.ts

# Ne pas compter les specs comme du code de prod / ignorer node_modules
sonar.exclusions=**/*.spec.ts,**/node_modules/**

# Java : classes compilées
sonar.java.binaries=back/build/classes/java/main

# Rapports de couverture
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info